---
- hosts: localhost
  connection: local

  vars_files:
    - vars/main.config.yml
    - vars/dotfiles.config.yml
    - vars/vimsetup.config.yml
    - vars/homebrew.config.yml

  roles:
    - role: dotfiles
      tags: ['dotfiles']
    - role: vimsetup
      tags: ['vimsetup']
    - role: geerlingguy.homebrew
      when: ansible_facts['os_family'] == "Darwin"
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: ansible_facts['os_family'] == "Darwin"
      tags: ['mas']
