---
- name: Ensure Ansible downloads directory exists.
  file:
    path: "{{ downloads }}"
    state: directory

- name: Ensure /etc/ansible directory exists.
  file:
    path: /etc/ansible
    state: directory
  become: true

- name: Am I running on Mac OS X?
  fail:
    msg: This playbook only runs on Mac OS X
  when: ansible_distribution != 'MacOSX'