---

- hosts: localhost
  connection: local

  vars:
    - user_name: michael


  tasks:
    - name: create vimdirs
      become: true
      become_user: "{{user_name}}"
      file: path={{ item }} state=directory
      with_items:
        - ~{{user_name}}/.vim/
        - ~{{user_name}}/.vim/autoload/
        - ~{{user_name}}/.vim/bundle/

    - name: Install Pathogen
      become: true
      become_user: "{{user_name}}"
      get_url:
        url: https://tpo.pe/pathogen.vim
        dest: ~{{user_name}}/.vim/autoload/pathogen.vim

    - name: Install vim plugins
      become: true
      become_user: "{{user_name}}"
      git: repo={{ item.a }} dest=~{{user_name}}/.vim/bundle/{{ item.b }}
      with_items:
        - {a: 'git@github.com:tpope/vim-fugitive.git', b: 'vim-fugitive'}
        - {a: 'git@github.com:tpope/vim-surround.git', b: 'vim-surround'}
        - {a: 'git@github.com:vim-airline/vim-airline.git', b: 'vim-airline'}
        - {a: 'git@github.com:nvie/vim-flake8.git', b: 'vim-flake8'}
        - {a: 'git@github.com:w0rp/ale.git', b: 'ale'}
