---
- name: Clone dotfiles
  ignore_errors: true
  become: true
  become_user: "{{ user_name }}"
  git:
    repo: git@github.com:michaelcoyote/dotfiles.git
    dest: "{{ home_dir }}/.dotfiles"
    accept_hostkey: true

- name: Install dotfiles
  become: true
  become_user: "{{ user_name }}"
  command: "{{ home_dir }}/.dotfiles/DFlink.sh"
  args:
    chdir: "{{ home_dir }}/.dotfiles"
