---
downloads: ~/.ansible-downloads/

user_name: "michael"
home_dir: "/Users/michael"  # "{{ lookup('env','HOME') }}"

configure_dotfiles: true
configure_sudoers: true
configure_terminal: false
configure_osx: false

dotfiles_repo: https://github.com/michaelcoyote/dotfiles.git
dotfiles_repo_local_destination: ~/Dropbox/Development/GitHub/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_upgrade_all_packages: true

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - tidwall/jj # need to figure out how to install jj
  - ag
  - autoconf
  - awscli
  - bash-completion
  - bats
  - doxygen
  - eslint
  - font-iosevka
  - gettext
  - gifsicle
  - git
  - gist
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - ipython
  - jq
  - kubectl
  - libevent
  - lynx
  - sqlite
  - mas
  - mcrypt
  - mosh
  - nmap
  - npm
  - readline
  - openssl
  - pandoc
  - pv
  - python
  - shellcheck
  - ssh-copy-id
  - tig
  - wget
  - wrk
  - yamllint

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - flux
  - licecap
  - macvim
  - oracle-jdk
  - sequel-pro
  - vagrant
  - virtualbox
  - typora
  - macpass
  - signal
  - minikube
# - firefox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - {id: 920404675, name: "Monodraw (1.3)"}
  - {id: 405843582, name: "Alfred (1.2)"}
  - {id: 918858936, name: "Airmail 3 (3.6.58)"}
  - {id: 803453959, name: "Slack (3.3.8)"}
  - {id: 497799835, name: "Xcode (10.2)"}
  - {id: 442160987, name: "Flycut (1.5)"}
  - {id: 1143641091, name: "SwiftoDo Desktop (3.0.0)"}

# No mas - left as a placeholder
# Pass in at command line w/
# --extra-vars "mas_email=stevejobs@apple.com mas_password=123foo_staple"
mas_email: "{{ lookup('env','MAS_EMAIL') }}"
mas_password: "{{ lookup('env', MAS_PASSWORD) }}"

osx_script: "~/.osx --no-restart"

vim_plugins:
  - {name: 'vim-fugitive', uri: 'git@github.com:tpope/vim-fugitive.git'}
  - {name: 'vim-airline', uri: 'git@github.com:vim-airline/vim-airline.git'}
  - {name: 'vim-flake8', uri: 'git@github.com:nvie/vim-flake8.git'}
  - {name: 'ale', uri: 'git@github.com:dense-analysis/ale.git'}

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
